export type CoolifyApplicationType = 'public' | 'private-github-app' | 'private-deploy-key' | 'dockerfile' | 'dockerimage' | 'dockercompose'

export interface CoolifyPrivateGitHubAppBody {
  project_uuid: string
  server_uuid: string
  environment_name: string
  environment_uuid: string
  github_app_uuid: string
  git_repository: string
  git_branch: string
  ports_exposes: string
  destination_uuid: string
  build_pack: string
  name: string
  description: string
  domains: string
  git_commit_sha: string
  docker_registry_image_name: string
  docker_registry_image_tag: string
  is_static: true
  static_image: string
  install_command: string
  build_command: string
  start_command: string
  ports_mappings: string
  base_directory: string
  publish_directory: string
  health_check_enabled: true
  health_check_path: string
  health_check_port: string
  health_check_host: string
  health_check_method: string
  health_check_return_code: 0
  health_check_scheme: string
  health_check_response_text: string
  health_check_interval: 0
  health_check_timeout: 0
  health_check_retries: 0
  health_check_start_period: 0
  limits_memory: string
  limits_memory_swap: string
  limits_memory_swappiness: 0
  limits_memory_reservation: string
  limits_cpus: string
  limits_cpuset: string
  limits_cpu_shares: 0
  custom_labels: string
  custom_docker_run_options: string
  post_deployment_command: string
  post_deployment_command_container: string
  pre_deployment_command: string
  pre_deployment_command_container: string
  manual_webhook_secret_github: string
  manual_webhook_secret_gitlab: string
  manual_webhook_secret_bitbucket: string
  manual_webhook_secret_gitea: string
  redirect: string
  instant_deploy: true
  dockerfile: string
  docker_compose_location: string
  docker_compose_raw: string
  docker_compose_custom_start_command: string
  docker_compose_custom_build_command: string
  docker_compose_domains: string[]
  watch_paths: string
  use_build_server: true
  is_http_basic_auth_enabled: true
  http_basic_auth_username: string
  http_basic_auth_password: string
  connect_to_docker_network: true
}

export interface CoolifyApplicationsBody {
  project_uuid: string
  server_uuid: string
  environment_name: string
  github_app_uuid: string
  git_repository: string
  git_branch: string
  ports_exposes: string
  destination_uuid: string
  build_pack: string
  name: string
  description: string
  domains: string
  git_commit_sha: string
  docker_registry_image_name: string
  docker_registry_image_tag: string
  is_static: boolean
  install_command: string
  build_command: string
  start_command: string
  ports_mappings: string
  base_directory: string
  publish_directory: string
  health_check_enabled: boolean
  health_check_path: string
  health_check_port: string
  health_check_host: string
  health_check_method: string
  health_check_return_code: number
  health_check_scheme: string
  health_check_response_text: string
  health_check_interval: number
  health_check_timeout: number
  health_check_retries: number
  health_check_start_period: number
  limits_memory: string
  limits_memory_swap: string
  limits_memory_swappiness: number
  limits_memory_reservation: string
  limits_cpus: string
  limits_cpuset: string
  limits_cpu_shares: number
  custom_labels: string
  custom_docker_run_options: string
  post_deployment_command: string
  post_deployment_command_container: string
  pre_deployment_command: string
  pre_deployment_command_container: string
  manual_webhook_secret_github: string
  manual_webhook_secret_gitlab: string
  manual_webhook_secret_bitbucket: string
  manual_webhook_secret_gitea: string
  redirect: string
  instant_deploy: boolean
  dockerfile: string
  docker_compose_location: string
  docker_compose_raw: string
  docker_compose_custom_start_command: string
  docker_compose_custom_build_command: string
  docker_compose_domains: string[]
  watch_paths: string
  use_build_server: boolean
  connect_to_docker_network: boolean
}

export interface CoolifyPrivateDeployKeyBody {
  project_uuid: string
  server_uuid: string
  environment_name: string
  environment_uuid: string
  private_key_uuid: string
  git_repository: string
  git_branch: string
  ports_exposes: string
  destination_uuid: string
  build_pack: string
  name: string
  description: string
  domains: string
  git_commit_sha: string
  docker_registry_image_name: string
  docker_registry_image_tag: string
  is_static: true
  static_image: string
  install_command: string
  build_command: string
  start_command: string
  ports_mappings: string
  base_directory: string
  publish_directory: string
  health_check_enabled: true
  health_check_path: string
  health_check_port: string
  health_check_host: string
  health_check_method: string
  health_check_return_code: 0
  health_check_scheme: string
  health_check_response_text: string
  health_check_interval: 0
  health_check_timeout: 0
  health_check_retries: 0
  health_check_start_period: 0
  limits_memory: string
  limits_memory_swap: string
  limits_memory_swappiness: 0
  limits_memory_reservation: string
  limits_cpus: string
  limits_cpuset: string
  limits_cpu_shares: 0
  custom_labels: string
  custom_docker_run_options: string
  post_deployment_command: string
  post_deployment_command_container: string
  pre_deployment_command: string
  pre_deployment_command_container: string
  manual_webhook_secret_github: string
  manual_webhook_secret_gitlab: string
  manual_webhook_secret_bitbucket: string
  manual_webhook_secret_gitea: string
  redirect: string
  instant_deploy: true
  dockerfile: string
  docker_compose_location: string
  docker_compose_raw: string
  docker_compose_custom_start_command: string
  docker_compose_custom_build_command: string
  docker_compose_domains: string[]
  watch_paths: string
  use_build_server: true
  is_http_basic_auth_enabled: true
  http_basic_auth_username: string
  http_basic_auth_password: string
  connect_to_docker_network: true
}

export interface CoolifyDockerfileBody {
  project_uuid: string
  server_uuid: string
  environment_name: string
  environment_uuid: string
  dockerfile: string
  build_pack: string
  ports_exposes: string
  destination_uuid: string
  name: string
  description: string
  domains: string
  docker_registry_image_name: string
  docker_registry_image_tag: string
  ports_mappings: string
  base_directory: string
  health_check_enabled: true
  health_check_path: string
  health_check_port: string
  health_check_host: string
  health_check_method: string
  health_check_return_code: 0
  health_check_scheme: string
  health_check_response_text: string
  health_check_interval: 0
  health_check_timeout: 0
  health_check_retries: 0
  health_check_start_period: 0
  limits_memory: string
  limits_memory_swap: string
  limits_memory_swappiness: 0
  limits_memory_reservation: string
  limits_cpus: string
  limits_cpuset: string
  limits_cpu_shares: 0
  custom_labels: string
  custom_docker_run_options: string
  post_deployment_command: string
  post_deployment_command_container: string
  pre_deployment_command: string
  pre_deployment_command_container: string
  manual_webhook_secret_github: string
  manual_webhook_secret_gitlab: string
  manual_webhook_secret_bitbucket: string
  manual_webhook_secret_gitea: string
  redirect: string
  instant_deploy: true
  use_build_server: true
  is_http_basic_auth_enabled: true
  http_basic_auth_username: string
  http_basic_auth_password: string
  connect_to_docker_network: true
}

export interface CoolifyDockerImageBody {
  project_uuid: string
  server_uuid: string
  environment_name: string
  environment_uuid: string
  docker_registry_image_name: string
  docker_registry_image_tag: string
  ports_exposes: string
  destination_uuid: string
  name: string
  description: string
  domains: string
  ports_mappings: string
  health_check_enabled: true
  health_check_path: string
  health_check_port: string
  health_check_host: string
  health_check_method: string
  health_check_return_code: 0
  health_check_scheme: string
  health_check_response_text: string
  health_check_interval: 0
  health_check_timeout: 0
  health_check_retries: 0
  health_check_start_period: 0
  limits_memory: string
  limits_memory_swap: string
  limits_memory_swappiness: 0
  limits_memory_reservation: string
  limits_cpus: string
  limits_cpuset: string
  limits_cpu_shares: 0
  custom_labels: string
  custom_docker_run_options: string
  post_deployment_command: string
  post_deployment_command_container: string
  pre_deployment_command: string
  pre_deployment_command_container: string
  manual_webhook_secret_github: string
  manual_webhook_secret_gitlab: string
  manual_webhook_secret_bitbucket: string
  manual_webhook_secret_gitea: string
  redirect: string
  instant_deploy: true
  use_build_server: true
  is_http_basic_auth_enabled: true
  http_basic_auth_username: string
  http_basic_auth_password: string
  connect_to_docker_network: true
}

export interface CoolifyDockerComposeBody {
  project_uuid: string
  server_uuid: string
  environment_name: string
  environment_uuid: string
  docker_compose_raw: string
  destination_uuid: string
  name: string
  description: string
  instant_deploy: true
  use_build_server: true
  connect_to_docker_network: true
}

export interface CoolifyApplicationsEnvsBody {
  key: string
  value: string
  is_preview: boolean
  is_build_time: boolean
  is_literal: boolean
  is_multiline: boolean
  is_shown_once: boolean
}